### ISSUE TITLE
Mouse over doesnt render description (just empty pop up) Free code camp

### ISSUE THREAD

**Issue by iphutch** [kommandr/browser-extension#17]
**Describe the bug**
<img width="1787" alt="Screen Shot 2021-06-30 at 9 24 31 AM" src="https://user-images.githubusercontent.com/21109162/123978006-20da7e80-d985-11eb-831c-ef49a0dcfbf0.png">

**To Reproduce**
https://www.freecodecamp.org/learn/front-end-libraries/bootstrap/use-responsive-design-with-bootstrap-fluid-containers

**Comment by ediardo** [comment]
Fixed in v4.7
