### ISSUE TITLE
CSS line number formatting inconsistent

### ISSUE THREAD

**Issue by iphutch** [kommandr/browser-extension#23]
**Describe the bug**
CSS snippets have weird formatting of line numbers in 4.8.2

**To Reproduce**
https://chartscss.org/docs/usage/#custom-styling

**Expected behavior**

**Screenshots**

<img width="778" alt="Screen Shot 2021-08-16 at 11 31 21 AM" src="https://user-images.githubusercontent.com/21109162/129605172-1fbcf649-4401-45af-995d-b4311cd6a078.png">

**Comment by ediardo** [comment]
Fixed in v4.8.3
