### ISSUE TITLE
mysqld, mysql

### ISSUE THREAD

**Issue by iphutch** [kommandr/browser-extension#4]
**To reproduce**
Paste a command that includes the attribute that needs attention.
```bash
mysqld
```

**Describe the problem with what is currently being rendered**
[x]Missing
[ ]Incorrect
[ ]Poorly worded
[ ]Other: Please describe

**Expected description**
If known, what is the definition of this command attribute.

**Language**
[x] English
[ ] Spanish

**Comment by d0st0r** [comment]
Definition changed and subcommands added.
