### ISSUE TITLE
Code blocks with &nbsp; don't show useful information

### ISSUE THREAD

**Issue by ediardo** [kommandr/browser-extension#5]
**Describe the bug**

**To Reproduce**
1. Go to https://www.atlassian.com/git/tutorials/git-ssh

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by d0st0r** [comment]
@ediardo  who needs to take action on this one? I'm not able to reproduce the error.

**Comment by ediardo** [comment]
> @ediardo who needs to take action on this one? I'm not able to reproduce the error.

This problem should be fixed on the Browser Extension by translating HTML Entities like `&nbsp;` into actual whitespaces that don't confuse the parser.

**Comment by ediardo** [comment]
Fixed
