### ISSUE TITLE
ffmpeg needs review

### ISSUE THREAD

**Issue by iphutch** [kommandr/browser-extension#6]
**To reproduce**
Paste a command that includes the attribute that needs attention.
```bash
ffmpeg -i input.avi -b:v 64k -bufsize 64k output.avi
```

**Describe the problem with what is currently being rendered**
[ ]Missing
[ ]Incorrect
[ ]Poorly worded
[x]Other: ffmpeg is uses options that like -b:v and -c:s

**Expected behavior**
Parser may need to be able to parse options with this format. 

**Language**
[x] English
[ ] Spanish

**Comment by d0st0r** [comment]
Added as requested
